[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
MKLSparse = "0c723cd3-b8cd-5d40-b370-ba682dde9aae"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"
ThreadedSparseCSR = "39591389-4884-462a-89e7-9edfce40b6eb"
